// <auto-generated />
namespace DGW_LP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class test91 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test91));
        
        string IMigrationMetadata.Id
        {
            get { return "201610251250415_test91"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
